
package view;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.types.ObjectId;
import modelo.Alquiler;
import dao.AlquilerDAO;
import controlador.AlquilerControlador;

/**
 *
 * @author halfa
 */
public class AlquilerFrame extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
    private AlquilerDAO alquilerDao;
    private AlquilerControlador alquilerControlador;

    /**
     * Creates new form AlquilerFrame
     */
    public AlquilerFrame() {
        initComponents();
        alquilerDao = new AlquilerDAO();
        alquilerControlador = new AlquilerControlador();
        setupTable();
        loadAlquiler();
        btnBorrar.setVisible(false);
        btnActualizar.setVisible(false);
        
    }
    private void setupTable() {
        String[] columnNames = {"ID", "Fecha Inicio", "Fecha Fin", "Total pago"};
        tableModel = new DefaultTableModel(columnNames, 0){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                // no permite que se modifique el id
                return columna != 0;
            }
        };
        tbAlquiler.setModel(tableModel);
    }
    
    //Recorriendo colecciones
    private void loadAlquiler(){
        tableModel.setRowCount(0);//Limpiando tabla
        List<Alquiler> alquileres = alquilerDao.findAllAlquileres();
        for(Alquiler a: alquileres){
            
            Object[] row = new Object[]{
                a.getId(),        
                a.getFechaInicio(),
                a.getFechaFin(),
                a.getTotalPago(),                
            };
            tableModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlquiler = new javax.swing.JTable();
        btnAgregarAlquiler = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlquilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAlquiler);

        btnAgregarAlquiler.setText("Agregar alquiler");
        btnAgregarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlquilerActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Se puede editar una fila al hacer click sobre ella");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnAgregarAlquiler))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnActualizar)))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrar)
                            .addComponent(btnAtras))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAlquiler)
                    .addComponent(btnAtras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //abre el frame para registrar un nuevo alquiler
    private void btnAgregarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerActionPerformed
        // TODO add your handling code here:
        new RegistroAlquilerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarAlquilerActionPerformed
    
    //Actualiza los datos de la fila seleccionada
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         //captura los datos del la fila
         int fila = tbAlquiler.getSelectedRow();
         ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
         String fechaInicio = (String)tableModel.getValueAt(fila, 1);       
         String fechaFin = (String)tableModel.getValueAt(fila, 2);
         double totalPago = (double)tableModel.getValueAt(fila, 3);
         //intenta actualizar el docuemto
         boolean ok = alquilerControlador.update(id, fechaInicio, fechaFin, totalPago);
          if (ok) {
            JOptionPane.showMessageDialog(this, "Los datos del vehiculo se ha actualizado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se pudo actualizar datos del vehiculo.");
        }
        //vuelve a cargar el frame
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    //borra un registro de la db
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        //captura los datos del la fila
        int fila = tbAlquiler.getSelectedRow();
        ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
        //intenta borrar el registro segun id
        boolean  ok = alquilerControlador.delete(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "El vehiculo se ha eliminado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se puedo eliminar el vehiculo.");
        }
        //vuelve a cargar el frame
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    //regresa al menu main
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void tbAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlquilerMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // un clic
            btnBorrar.setVisible(true);
            btnActualizar.setVisible(true);
        }
    }//GEN-LAST:event_tbAlquilerMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarAlquiler;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlquiler;
    // End of variables declaration//GEN-END:variables
}
