/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import org.bson.types.ObjectId;
import controlador.ClienteControlador;

/**
 *
 * @author denis
 */
public class ClientesFrame extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private ClienteDAO clienteDao;
    private ClienteControlador clienteC;
    
    /**
     * Creates new form ClientesFrame
     */
    
    //constructor
    public ClientesFrame() {
        initComponents();
        clienteDao = new ClienteDAO();
        clienteC = new ClienteControlador();
        setupTable();
        loadClientes();
        btnBorrar.setVisible(false);
        btnActualizar.setVisible(false);
    }
    
    //Creando las columnas para la tabla
    private void setupTable() {
        String[] columnNames = {"ID", "Nombres", "Apellidos", "Licencia", "Telefono", "Correo"};
        tableModel = new DefaultTableModel(columnNames, 0){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                // no permite que se modifique el id
                return columna != 0;
            }
        };
        tbClientes.setModel(tableModel);
    }
    //Recorriendo colecciones
    private void loadClientes(){
        tableModel.setRowCount(0);//Limpiando tabla
        List<Cliente> clientes = clienteDao.findAllClientes();
        for(Cliente c: clientes){
            Object[] row = new Object[]{
                c.getId(),
                c.getNombre(),
                c.getApellido(),
                c.getLicencia(),
                c.getTelefono(),
                c.getCorreo()
            };
            tableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        btnAgregar.setText("Agregar cliente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actulizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Al hacer click en una fila la puede editar y borrarla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtras)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //desencadena evento al hacer clic en los elemento de la tabla
    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // un clic
            btnBorrar.setVisible(true);
            btnActualizar.setVisible(true);
        }
       
    }//GEN-LAST:event_tbClientesMouseClicked

    //desencadena evento del boton agregar
    //lanza el frame para registrar un nuevo cliente
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new RegistroClienteFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    //desencadena el vento del boton atras. Regresa al menu main
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    //Desencadena el veneto al hacer cliac en el boton borrar
    //borra un registro de la base de datos de clientes
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        //captura los datos del la fila
        int fila = tbClientes.getSelectedRow(); 
        ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
        //intenta borrar el registro segun id
        boolean  ok = clienteC.delete(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "El cliente se ha eliminado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se puedo eliminar el cliente.");
        }
        //vuelve a cargar el frame
        new ClientesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarActionPerformed

    //desencadena el evento al hacer clic en el boton acctualizar alcualiza los datos editados de una clolumna
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         //captura los datos del la fila
        int fila = tbClientes.getSelectedRow(); 
        ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
        String nombres = (String)tableModel.getValueAt(fila, 1);
        String apellidos = (String)tableModel.getValueAt(fila, 2);
        String licencia = (String)tableModel.getValueAt(fila, 3);
        String telefono = (String)tableModel.getValueAt(fila, 4);
        String correo = (String)tableModel.getValueAt(fila, 5);
        System.out.println(licencia);
        //intenta actualizar el docuemto
        boolean  ok = clienteC.update(id, nombres, apellidos, licencia, telefono, correo);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Los datos del cliente se ha actualizado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se pudo actualizar datos del cliente.");
        }
        //vuelve a cargar el frame
        new ClientesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables
}
