
package view;
import controlador.AlquilerControlador;
import javax.swing.JOptionPane;


/**
 *
 * @author halfa
 */
public class RegistroAlquilerFrame extends javax.swing.JFrame {
    
    private AlquilerControlador controlador = new AlquilerControlador();

    
    /**
     * Creates new form RegistroAlquilerFrame
     */
    public RegistroAlquilerFrame() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLFechaInicio = new javax.swing.JLabel();
        jLFechaFin = new javax.swing.JLabel();
        jLTotalPago = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();
        btnGuardarAlq = new javax.swing.JButton();
        btnCancelarAlq = new javax.swing.JButton();
        txtTotalPago = new javax.swing.JTextField();
        jNombre = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtVehiculo = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtNombreCl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLFechaInicio.setText("Fecha inicio de alquiler");

        jLFechaFin.setText("Fecha fin de alquiler");

        jLTotalPago.setText("Total pago de alquiler");

        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        btnGuardarAlq.setText("Guardar");
        btnGuardarAlq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlqActionPerformed(evt);
            }
        });

        btnCancelarAlq.setText("Cancelar");
        btnCancelarAlq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAlqActionPerformed(evt);
            }
        });

        txtTotalPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPagoKeyTyped(evt);
            }
        });

        jNombre.setText("Nombre de cliente");

        jNombre1.setText("Nombre empleado");

        jLabel1.setText("Vehiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnGuardarAlq)
                        .addGap(110, 110, 110)
                        .addComponent(btnCancelarAlq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFechaInicio)
                            .addComponent(jLFechaFin)
                            .addComponent(jNombre)
                            .addComponent(jNombre1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLTotalPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtFechaFin)
                            .addComponent(txtTotalPago)
                            .addComponent(txtVehiculo)
                            .addComponent(txtEmpleado)
                            .addComponent(txtNombreCl))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFechaInicio))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotalPago)
                    .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(txtNombreCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre1)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAlq)
                    .addComponent(btnCancelarAlq))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed
    //crea un objeto alquiler y lo registra en la base de datos
    private void btnGuardarAlqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlqActionPerformed
        // TODO add your handling code here:
        //atributos del alquiler
        String fechaInicio = txtFechaInicio.getText().trim();
        String fechaFin = txtFechaFin.getText().trim();
        double totalPago = Double.parseDouble(txtTotalPago.getText().trim());
        String nombreCl = txtNombreCl.getText().trim();
        String empleado = txtEmpleado.getText().trim();
        String codigo = txtVehiculo.getText().trim();
        
        //Valida la entrada de totalPago
        if(totalPago<0){
            throw new IllegalArgumentException("El pago total de alquiler no puede ser negativo");
        }
        if(fechaInicio.isEmpty() || fechaFin.isEmpty() || nombreCl.isEmpty() || empleado.isEmpty() || codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        //intenta crear el registro en la db
        boolean ok = controlador.register(fechaInicio, fechaFin, totalPago);
        if (ok) {
            JOptionPane.showMessageDialog(this, "El Alquiler se ha registrado con exito.");
            dispose();
            // Retornar al login si solo existe
            new AlquilerFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Parece que el Alquiler ya esta registrado.");
        }

    }//GEN-LAST:event_btnGuardarAlqActionPerformed
    
    //Cierra el frame y regresa al main
    private void btnCancelarAlqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAlqActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarAlqActionPerformed
    
    
    //bloquea la entrada de texto cuando se tipean caracteres no deseados
    private void txtTotalPagoKeyTyped(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // No permite escribir si no es número
        }
    }                               

/*
    private void txtTotalPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPagoKeyTyped

    }//GEN-LAST:event_txtTotalPagoKeyTyped
*/    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlquilerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAlq;
    private javax.swing.JButton btnGuardarAlq;
    private javax.swing.JLabel jLFechaFin;
    private javax.swing.JLabel jLFechaInicio;
    private javax.swing.JLabel jLTotalPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNombre1;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtNombreCl;
    private javax.swing.JTextField txtTotalPago;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}
