/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controlador.VehiculoControlador;
import dao.VehiculoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedor;
import modelo.TipoProveedor;
import modelo.TipoVehiculo;
import modelo.Vehiculo;
import org.bson.types.ObjectId;

/**
 *
 * @author denis
 */
public class VehiculosFrame extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private VehiculoDAO vehiculoDao;
    private VehiculoControlador vehiculoControlador;
    /**
     * Creates new form VehiculosFrame
     */
    public VehiculosFrame() {
        initComponents();
        vehiculoDao = new VehiculoDAO();
        vehiculoControlador = new VehiculoControlador();
        setupTable();
        loadClientes();
        btnBorrar.setVisible(false);
        btnActualizar.setVisible(false);
    }
    
    //Creando las columnas para la tabla
    private void setupTable() {
        String[] columnNames = {"ID", "Codigo", "Marca", "Modelo", "Año", "Tipo", "Precio/dia", "Disponible", "Mantenimiento", "Repuestos"};
        tableModel = new DefaultTableModel(columnNames, 0){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                // no permite que se modifique el id
                return columna != 0;
            }
        };
        tbVehiculos.setModel(tableModel);
    }
    //Recorriendo colecciones
    private void loadClientes(){
        Proveedor mantenimiento = null;
        Proveedor repuestos = null;
        
        tableModel.setRowCount(0);//Limpiando tabla
        List<Vehiculo> vehiculos = vehiculoDao.findAllVehiculos();
        
        for(Vehiculo v: vehiculos){
            for(Proveedor p: v.getProveedores()){
                if(p.getTipo() == TipoProveedor.MANTENIMIENTO )
                    mantenimiento = p;
                else
                    repuestos = p;
            }
            Object[] row = new Object[]{
                v.getId(),
                v.getCodigo(),
                v.getMarca(),
                v.getModelo(),
                v.getAño(),
                v.getTipo().toString(),
                v.getPrecioDia(),
                v.isDisponible(),
                mantenimiento.getNombre(),
                repuestos.getNombre()
            };
            tableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar Vehiculo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actulizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Al hacer click en una fila la puede editar y borrarla");

        tbVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVehiculosMouseClicked(evt);
            }
        });
        tbVehiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbVehiculosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbVehiculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1)))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //abre el frame para registrar un nuevo vehiculo
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new RegistroVehiculosFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    //Actualiza los datos de la fila seleccionada
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        //captura los datos del la fila
        int fila = tbVehiculos.getSelectedRow();
        ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
        String codigo = (String)tableModel.getValueAt(fila, 1);
        String marca = (String)tableModel.getValueAt(fila, 2);
        String modelo = (String)tableModel.getValueAt(fila, 3);
        int año = (int)tableModel.getValueAt(fila, 4);
        TipoVehiculo tipo = TipoVehiculo.valueOf(tableModel.getValueAt(fila, 5).toString());
        double precio = (double)tableModel.getValueAt(fila, 6);
        boolean disponible = (boolean)tableModel.getValueAt(fila, 7);
        Proveedor provM = new Proveedor((String)tableModel.getValueAt(fila, 8), TipoProveedor.MANTENIMIENTO);
        Proveedor provR = new Proveedor((String)tableModel.getValueAt(fila, 9), TipoProveedor.REPUESTOS);
        List<Proveedor>proveedores = new ArrayList<>();
        proveedores.add(provM);
        proveedores.add(provR);
        //intenta actualizar el docuemto
        boolean  ok = vehiculoControlador.update(id, codigo, marca, modelo, año, tipo,precio,proveedores, disponible);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Los datos del vehiculo se ha actualizado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se pudo actualizar datos del vehiculo.");
        }
        //vuelve a cargar el frame
        new ClientesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    //borra un registro de la db
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        //captura los datos del la fila
        int fila = tbVehiculos.getSelectedRow();
        ObjectId id = (ObjectId) tableModel.getValueAt(fila, 0);
        //intenta borrar el registro segun id
        boolean  ok = vehiculoControlador.delete(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "El vehiculo se ha eliminado con exito.");
            dispose();
            // Retornar al login si solo existe
            new MainMenuFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error no se puedo eliminar el vehiculo.");
        }
        //vuelve a cargar el frame
        new ClientesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarActionPerformed

    //regresa al menu main
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    //muestra los botones de actualizar y borrar al hacer clic en la tabla
    private void tbVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVehiculosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // un clic
            btnBorrar.setVisible(true);
            btnActualizar.setVisible(true);
        }

    }//GEN-LAST:event_tbVehiculosMouseClicked

    private void tbVehiculosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbVehiculosKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tbVehiculosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVehiculos;
    // End of variables declaration//GEN-END:variables
}
